create database dienwagen;


CREATE TABLE DEALER_DETAILS(
    DEALER_ID INTEGER not null,
    DEALER_NAME VARCHAR(50) not null,
    ADDRESS VARCHAR(100) not null,
    CONTACT_NO VARCHAR(20) not null,
    EMAIL_ID VARCHAR(50) not null UNIQUE,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
	PRIMARY KEY(DEALER_ID));
    

    
CREATE TABLE LOGIN_DETAILS(
    USER_ID INTEGER NOT NULL,
    USER_NAME VARCHAR(30) NOT NULL,
    PWD VARCHAR(100) NOT NULL,
    DEALER_ID INTEGER NOT NULL REFERENCES DEALER_DETAILS(DEALER_ID),
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
	PRIMARY KEY(USER_ID));
    
           
CREATE TABLE ROLES(
	ROLE_ID INTEGER NOT NULL,
    ROLE_NAME VARCHAR(10) NOT NULL,
    PRIMARY KEY(ROLE_ID));  
     
    
CREATE TABLE CUSTOMER_DETAILS(
    CUST_ID INTEGER NOT NULL,
    CUST_NAME VARCHAR(100) NOT NULL,
    MOBILE_NO VARCHAR(20) NOT NULL,
    EMAIL_ID VARCHAR(50),
    ADDRESS VARCHAR(100),
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(CUST_ID));
    
       
    
CREATE TABLE VEHICLE_MODEL(
    MODEL_ID INTEGER NOT NULL,
    MODEL_NAME VARCHAR(50) NOT NULL,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(MODEL_ID));
    
 	   
    
CREATE TABLE VEHICLE_BODY(
    BODY_ID INTEGER NOT NULL,
    BODY_TYPE VARCHAR(50) NOT NULL,
    MODEL_ID INTEGER NOT NULL REFERENCES VEHICLE_MODEL(MODEL_ID),
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(BODY_ID));
    
    
       
CREATE TABLE VEHICLE_ENGINE(
    ENGINE_ID INTEGER NOT NULL,
    ENGINE_NAME VARCHAR(50) NOT NULL,
    MODEL_ID INTEGER NOT NULL REFERENCES VEHICLE_MODEL(MODEL_ID),
    PRICE INTEGER NOT NULL,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(ENGINE_ID));
    
   
    
CREATE TABLE VEHICLE_LINE(
    LINE_ID INTEGER NOT NULL,
    LINE_NAME VARCHAR(50) NOT NULL,
    MODEL_ID INTEGER NOT NULL REFERENCES VEHICLE_MODEL(MODEL_ID),
    ENGINE_ID INTEGER NOT NULL REFERENCES VEHICLE_ENGINE(ENGINE_ID),
    PRICE INTEGER NOT NULL DEFAULT 0,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(LINE_ID));   
    
    
CREATE TABLE VEHICLE_EQUIPMENT(
    EQUIPMENT_ID INTEGER NOT NULL,
    EQUIPMENT_NAME VARCHAR(50) NOT NULL,
    MODEL_ID INTEGER NOT NULL REFERENCES VEHICLE_MODEL(MODEL_ID),
	ENGINE_ID INTEGER NOT NULL REFERENCES VEHICLE_ENGINE(ENGINE_ID),
    PRICE INTEGER NOT NULL DEFAULT 0,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(EQUIPMENT_ID));

CREATE TABLE VEHICLE_PAINT(
    PAINT_ID INTEGER NOT NULL,
    PAINT_NAME VARCHAR(50) NOT NULL,
    PAINT_TYPE VARCHAR(10) DEFAULT 'EXTERNAL',
    MODEL_ID INTEGER NOT NULL REFERENCES VEHICLE_MODEL(MODEL_ID),
    PRICE INTEGER NOT NULL DEFAULT 0,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(PAINT_ID));
    
CREATE TABLE VEHICLE_TRANSACTION(
    TRANSACTION_ID INTEGER NOT NULL,
    CUST_ID INTEGER NOT NULL REFERENCES CUSTOMER_DETAILS(CUST_ID),
    LINE_ID INTEGER NOT NULL REFERENCES VEHICLE_LINE(LINE_ID),
    MODEL_ID INTEGER NOT NULL REFERENCES VEHICLE_MODEL(MODEL_ID),
    BODY_ID INTEGER NOT NULL REFERENCES VEHICLE_BODY(BODY_ID),
    ENGINE_ID INTEGER NOT NULL REFERENCES VEHICLE_ENGINE(ENGINE_ID),
    EQUIPMENT_ID INTEGER NOT NULL REFERENCES VEHICLE_EQUIPMENT(EQUIPMENT_ID),
    INT_PAINT_ID INTEGER NOT NULL REFERENCES VEHICLE_PAINT(PAINT_ID),
    EXT_PAINT_ID INTEGER NOT NULL REFERENCES VEHICLE_PAINT(PAINT_ID),
    DISCOUNT INTEGER NOT NULL DEFAULT 0,
    TOTAL_PRICE INTEGER NOT NULL DEFAULT 0,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(TRANSACTION_ID));    
    
CREATE TABLE ORDER_DETAILS(
    ORDER_ID INTEGER NOT NULL,
    TRANSACTION_ID INTEGER NOT NULL REFERENCES VEHICLE_TRANSACTION(TRANSACTION_ID),
    ORDER_DATE DATE NOT NULL,
    EST_DELIVERY_DATE DATE NOT NULL,
    ACTUAL_DELIVERY_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(20) NOT NULL,
    TRANSPORT_COST INTEGER NOT NULL DEFAULT 0,
    TOTAL_PRICE INTEGER NOT NULL DEFAULT 0,
    LAST_UPDATED_BY VARCHAR(50),
    LAST_UPDATED_TIME TIMESTAMP,
    PRIMARY KEY(ORDER_ID));    
    
    
    DROP TABLE DEALER_DETAILS;
    DROP TABLE LOGIN_DETAILS;
    DROP TABLE ROLES;
    DROP TABLE CUSTOMER_DETAILS;    
	DROP TABLE VEHICLE_MODEL;     
    DROP TABLE VEHICLE_BODY;
    DROP TABLE VEHICLE_ENGINE;
    DROP TABLE VEHICLE_LINE;
    DROP TABLE VEHICLE_EQUIPMENT;
    DROP TABLE VEHICLE_PAINT;
    DROP TABLE VEHICLE_TRANSACTION;
    DROP TABLE ORDER_DETAILS; 
    --EXECUTE DROP OPERATION BOTTOM TO TOP
    
    /
